 
Traceback (most recent call last):
  File "C:\telegram_bot\app.py", line 13, in <module>
    handlers=[logging.FileHandler("bot.log"), logging.StreamHandler()],
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\StiqWiz\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1219, in __init__
    StreamHandler.__init__(self, self._open())
                                 ~~~~~~~~~~^^
  File "C:\Users\StiqWiz\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1248, in _open
    return open_func(self.baseFilename, self.mode,
                     encoding=self.encoding, errors=self.errors)
PermissionError: [Errno 13] Permission denied: 'C:\\telegram_bot\\bot.log'
2025-09-21 00:53:00,123 | INFO | root | Starting bot...
2025-09-21 00:53:00,123 | INFO | aiogram.dispatcher | Start polling
2025-09-21 00:53:00,437 | INFO | aiogram.dispatcher | Run polling for bot @my_tipo_test_bot id=8310053894 - 'my_tipo_test'
2025-09-21 00:53:08,256 | INFO | aiogram.event | Update id=266230396 is handled. Duration 353 ms by bot id=8310053894
2025-09-21 00:53:10,141 | INFO | aiogram.event | Update id=266230397 is not handled. Duration 0 ms by bot id=8310053894
2025-09-21 00:53:17,162 | INFO | aiogram.event | Update id=266230398 is handled. Duration 124 ms by bot id=8310053894
2025-09-21 00:53:19,944 | INFO | aiogram.event | Update id=266230399 is not handled. Duration 0 ms by bot id=8310053894
2025-09-21 00:53:21,992 | INFO | aiogram.event | Update id=266230400 is handled. Duration 127 ms by bot id=8310053894
2025-09-21 00:53:24,237 | INFO | aiogram.event | Update id=266230401 is not handled. Duration 0 ms by bot id=8310053894
2025-09-21 00:53:25,594 | INFO | aiogram.event | Update id=266230402 is not handled. Duration 0 ms by bot id=8310053894
